#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --account=m1727
#SBATCH --constraint=cpu
#SBATCH --job-name=fid2
#SBATCH --output=fid2.log
#SBATCH --mail-type=END

# You can create this environment as described in the readme.
module load python
conda activate ./env

export OMP_PROC_BIND=true
export OMP_PLACES=threads
export OMP_NUM_THREADS=1
mpirun -n 128 python cosmogrid_driver.py ridges --fiducial
