#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=4:00:00
#SBATCH --nodes=1
#SBATCH --account=des
#SBATCH --constraint=cpu
#SBATCH --job-name=desy3-fid4
#SBATCH --output=desy3-fid4.log


# You can create this environment as described in the readme.
module load python
conda activate ./env

export OMP_PROC_BIND=true
export OMP_PLACES=threads
export OMP_NUM_THREADS=1
mpirun -n 128 python -c "import cosmogrid_driver as c;c.fiducial('noisy-shear')"
