#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=40:00:00
#SBATCH --nodes=1
#SBATCH --account=des
#SBATCH --constraint=cpu
#SBATCH --job-name=desy3-step4
#SBATCH --output=desy3-step4c.log


# You can create this environment as described in the readme.
module load python
conda activate ./env


export OMP_PROC_BIND=true
export OMP_PLACES=threads
export OMP_NUM_THREADS=1
mpirun -n 128 python cosmogrid_driver.py shear --num-groups=4 --group=$1 &> step4.$1.log

